[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# we need to do remapping when we add any library in foundry as you can see below
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
# ffi true allow foundry to run commands directly on your machines
# ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
